// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package feedback

import (
	"knowledge-system-api/api/feedback"
)

type ControllerV1 struct{}

func NewV1() feedback.IFeedbackV1 {
	return &ControllerV1{}
}
