// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"knowledge-system-api/internal/dao/internal"
)

// knowledgeDao is the data access object for the table knowledge.
// You can define custom methods on it to extend its functionality as needed.
type knowledgeDao struct {
	*internal.KnowledgeDao
}

var (
	// Knowledge is a globally accessible object for table knowledge operations.
	Knowledge = knowledgeDao{internal.NewKnowledgeDao()}
)

// Add your custom methods and functionality below.
